/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Dimension;
import javax.swing.JInternalFrame;


/**
 *
 * @author Usser
 */
public class PanelPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PanelPrincipal
     */
    public PanelPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);//centrado
        this.setExtendedState(MAXIMIZED_BOTH);//ocupar todo el ancho y alto
    }

   

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaPrincipal = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuMenuSalir = new javax.swing.JMenuItem();
        mnuVentas = new javax.swing.JMenu();
        mnuVenGenerar = new javax.swing.JMenuItem();
        mnuMantenimiento = new javax.swing.JMenu();
        mnuManCliente = new javax.swing.JMenuItem();
        mnuManProducto = new javax.swing.JMenuItem();
        mnuReporte = new javax.swing.JMenu();
        mnuReporteVentas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(28, 33, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 992, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
        );

        VentanaPrincipal.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout VentanaPrincipalLayout = new javax.swing.GroupLayout(VentanaPrincipal);
        VentanaPrincipal.setLayout(VentanaPrincipalLayout);
        VentanaPrincipalLayout.setHorizontalGroup(
            VentanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        VentanaPrincipalLayout.setVerticalGroup(
            VentanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(VentanaPrincipal, java.awt.BorderLayout.CENTER);

        mnuMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/inicio.png"))); // NOI18N
        mnuMenu.setText("Menu");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ayuda.png"))); // NOI18N
        jMenuItem1.setText("Ayuda");
        mnuMenu.add(jMenuItem1);

        mnuMenuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/exit.png"))); // NOI18N
        mnuMenuSalir.setText("Salir");
        mnuMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMenuSalirActionPerformed(evt);
            }
        });
        mnuMenu.add(mnuMenuSalir);

        jMenuBar1.add(mnuMenu);

        mnuVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ventas.png"))); // NOI18N
        mnuVentas.setText("Ventas");

        mnuVenGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ventas2.png"))); // NOI18N
        mnuVenGenerar.setText("Generar Venta");
        mnuVenGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVenGenerarActionPerformed(evt);
            }
        });
        mnuVentas.add(mnuVenGenerar);

        jMenuBar1.add(mnuVentas);

        mnuMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/mantenimiento.png"))); // NOI18N
        mnuMantenimiento.setText("Mantenimiento");

        mnuManCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cliente.png"))); // NOI18N
        mnuManCliente.setText("Cliente");
        mnuManCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManClienteActionPerformed(evt);
            }
        });
        mnuMantenimiento.add(mnuManCliente);

        mnuManProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/producto2.png"))); // NOI18N
        mnuManProducto.setText("Producto");
        mnuManProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManProductoActionPerformed(evt);
            }
        });
        mnuMantenimiento.add(mnuManProducto);

        jMenuBar1.add(mnuMantenimiento);

        mnuReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/report.png"))); // NOI18N
        mnuReporte.setText("Reporte");

        mnuReporteVentas.setText("Reporte de ventas");
        mnuReporte.add(mnuReporteVentas);

        jMenuBar1.add(mnuReporte);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMenuSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_mnuMenuSalirActionPerformed

    
    //Centrar internal frame
    
    private void mnuVenGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVenGenerarActionPerformed
        // TODO add your handling code here:
        VentasForm vf=new VentasForm();
        CentrarVentana(vf);//metodo
    }//GEN-LAST:event_mnuVenGenerarActionPerformed

    private void mnuManClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManClienteActionPerformed
        // TODO add your handling code here:
        
        ClienteForm cf=new ClienteForm();
        CentrarVentana(cf);        
    }//GEN-LAST:event_mnuManClienteActionPerformed

    private void mnuManProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManProductoActionPerformed
        // TODO add your handling code here:
        ProductosForm pf=new ProductosForm();
        CentrarVentana(pf);
    }//GEN-LAST:event_mnuManProductoActionPerformed

    void CentrarVentana(JInternalFrame frame){
        VentanaPrincipal.add(frame);
        Dimension dimension=VentanaPrincipal.getSize();
        Dimension Dframe=frame.getSize();
        frame.setLocation((dimension.width -Dframe.height)/2,(dimension.height-Dframe.width)/2);
        frame.show();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane VentanaPrincipal;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem mnuManCliente;
    private javax.swing.JMenuItem mnuManProducto;
    private javax.swing.JMenu mnuMantenimiento;
    private javax.swing.JMenu mnuMenu;
    private javax.swing.JMenuItem mnuMenuSalir;
    private javax.swing.JMenu mnuReporte;
    private javax.swing.JMenuItem mnuReporteVentas;
    private javax.swing.JMenuItem mnuVenGenerar;
    private javax.swing.JMenu mnuVentas;
    // End of variables declaration//GEN-END:variables
}
